version: '3.8'
services:
  web:
    build: .
    image: brasil_convenios:latest
    ports:
      - "5002:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
